In [22]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
sess = tf.Session()

x= np.ones((3,3))
x_data = x.astype('float32')
print x_data
print "="*20
x_data = np.reshape(x_data, [1, 3, 3, 1])

print x_data

w = np.ones([2,2])
print w
print "="*20
w = tf.cast(tf.reshape(w, [2, 2, 1, 1]), "float")
# print w.eval()

print tf.nn.conv2d(x_data, w, [1, 1, 1, 1], 'SAME').eval(session=sess)
print "2="*20

l1 = tf.nn.relu(tf.nn.conv2d(x_data, w, [1, 1, 1, 1], 'SAME'))
print l1.eval(session=sess)
print "="*20

l2 = tf.nn.max_pool(l1, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME', name='l1_pool')
print l2.eval(session=sess)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[[[ 1.]
   [ 1.]
   [ 1.]]

  [[ 1.]
   [ 1.]
   [ 1.]]

  [[ 1.]
   [ 1.]
   [ 1.]]]]
[[ 1.  1.]
 [ 1.  1.]]
[[[[ 4.]
   [ 4.]
   [ 2.]]

  [[ 4.]
   [ 4.]
   [ 2.]]

  [[ 2.]
   [ 2.]
   [ 1.]]]]
2=2=2=2=2=2=2=2=2=2=2=2=2=2=2=2=2=2=2=2=
[[[[ 4.]
   [ 4.]
   [ 2.]]

  [[ 4.]
   [ 4.]
   [ 2.]]

  [[ 2.]
   [ 2.]
   [ 1.]]]]
[[[[ 4.]
   [ 2.]]

  [[ 2.]
   [ 1.]]]]


In [21]:
t = tf.constant(42.0)
u = tf.constant(37.0)
tu = tf.multiply(t, u)
ut = tf.multiply(u, t)
with sess.as_default():
   tu.eval()  # runs one step
   ut.eval()  # runs one step
   print tu.eval()
   print ut.eval()
   sess.run([tu, ut])  # evaluates both tensors in a single step

1554.0
1554.0
